### PR TITLE
Fixes for `run.sh`

### PR DESCRIPTION
**Pull request by ccare**
I think these final tweaks are sufficient to run the test-runner in our environment. If you're happy to merge this, I can deploy from the `remote-elm-home` branch and smoke test, then you can rebase/reset master as you see fit.

### CODE REVIEW

**Comment by ccare** [comment]
closes #1

**Review by ceddlyburge — APPROVED** [review]

**Comment by ccare** [comment]
Thanks!

**Comment by ccare** [comment]
Any chance one of you could merge this? I don't have access.

**Comment by mpizenberg** [comment]
Looks good, thank you

**Pull request merged**
