### PR TITLE
Prepare tests runner for elm-test-rs

### PR DESCRIPTION
**Pull request by mpizenberg**
Improvements of the tests runner for elm.

- Use a 2-stages Docker build for a lighter runner container
- Create ~/.elm cache in the build stage, based on the `templates/elm.json` file of the elm track
- Use elm-test-rs instead of elm-test (not finalized yet, waiting on `--report exercism` option in the making)

### CODE REVIEW

**Comment by mpizenberg** [comment]
I'm struggling with how to make the elm compiler not hang. Normally, if the `elm.json` did not change since last time we compile, the compiler should assume that dependencies are good and immediately compile stuff. But if `elm.json` is updated, the elm compiler checks the dependencies, and for that it does some weird network interaction, resulting in 5s of hanging when there is no network.

So I put much care in trying to keep files timestamps, by using `tar` to create and extract an archive containing `.elm`, `elm.json` and `elm-stuff`. Yet, when running `bin/run-in-docker.sh`, we spend more than 5s in the elm compiler where this should take less then 1s. This (tar) is obviously not enough to prevent the network hang of the elm compiler, and I'd like to figure out how to fix it.

**Comment by mpizenberg** [comment]
I've added tinyproxy to set a small proxy configured to fail all http requests. This effectively makes the elm compiler immediately switch to its offline mode and prevents the 5s hang :) 

I've also added a line to "un-skip" all the skipped tests in the `tests/Tests.elm` file.

**Comment by mpizenberg** [comment]
Alright I think this is ready for review. Here is a recap of the changes:
- Now using a 2-stage Docker build, making the final container smaller, from 232MB down to 162MB.
- I've added a proxy server (tinyproxy) configured to fail all requests. This effectively forces the elm compiler to immediately switch to offline mode and prevents a weird 5 seconds hang otherwise observed.
- The elm cache inside `~/.elm/` is now generated by the build step of the container, based on the `elm.json` template file of the exercism/elm repository so it is the same as the one used to run tests in that repo. Previously we had manually pre-package a `~/.elm/` dir and we used to download it during the container build.
- We are using `jq` now to generate the `results.json` in case the tests runner errors. This is much cleaner than the previous shell script.
- The tests runner used is now [elm-test-rs](https://github.com/mpizenberg/elm-test-rs) instead of [elm-test](https://github.com/rtfeldman/node-test-runner). This brings numerous advantages such as:
    - It has a `--report exercism` option so we don't need the post-processing python script anymore. This removes both the file and the need to have python installed in the container.
    - It is faster than elm-test. For a small project like those that will run for exercises, it brings the timing down from roughly 1.8s to roughly 0.3s. Combined with the fact that we shaved 5s thanks to the proxy trick, this new tests runner feels instantaneous compared to the old one.
    - It is a portable executable so we are now free from npm. Both elm and elm-test-rs can be installed by downloading an executable. This means I removed the `package.json` which is not needed anymore.

**Comment by mpizenberg** [comment]
PS: the windows script `run-in-docker.ps1` needs a small update to match the few changes in `run-in-docker.sh`.

**Comment by mpizenberg** [comment]
Excited to be able to test this update of the tests runner once #10 (which is also ready for merge) is merged :)

**Review by ErikSchierboom — APPROVED** [review]
The list of improvements looks impressive! Fantastic work.

**Pull request merged**
