### PR TITLE
Automatically push Docker image to Docker Hub

### PR DESCRIPTION
**Pull request by ErikSchierboom**
The [v3 development environment](https://github.com/exercism/development-environment/) uses Docker images from Docker Hub for all the tooling.
This allows for easy testing of the various tooling components (analyzers/representer/test-runners).

This PR adds a GitHub Actions workflow to automatically build and push a new Docker image whenever something is merged to master.

See https://github.com/exercism/v3/issues/2727

### CODE REVIEW

**Comment by mpizenberg** [comment]
@ErikSchierboom  I've updated this action to V2 and wanted to try it on PR but it seems the `DOCKERHUB_TOKEN` secret is missing. Is this because we are on PR and not on push or is it truly missing? I can't tell since I've not access to the repo parameters.

**Comment by ErikSchierboom** [comment]
@iHiD Could you add the secret?

**Comment by iHiD** [comment]
It's `DOCKERHUB_USERNAME` and `DOCKERHUB_PASSWORD`. Both are present.

**Review by mpizenberg — APPROVED** [review]
Thanks, I must have changed the secret by mistake when updating to V2. This is ready for review. @ErikSchierboom you can't review your own PR so I approved it and if you are ok with it, you can just merge it.

**Comment by ErikSchierboom** [comment]
Merged! I'm using your work on using the new Docker build-push action to update the C# test runner too: https://github.com/exercism/csharp-test-runner/pull/36 That PR also attempts to merge the two existing Docker publishing workflows into one workflow. Thanks for the work!

**Pull request merged**
