### PR TITLE
Copy docker CI from C#

### PR DESCRIPTION
**Pull request by mpizenberg**

### CODE REVIEW

**Comment by mpizenberg** [comment]
This PR (and the one in the C# repo) are trying to improve CI by regrouping DockerHub and ECR in the same flow, using the v2 of the docker action.

Currently, we are waiting on @iHiD for the addition of the following secrets: `AWS_ACCOUNT_ID` and `AWS_REGION`, used to generate the environment variable `ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com`

**Comment by iHiD** [comment]
These are added. @ErikSchierboom edited the script FYI.

**Comment by ErikSchierboom** [comment]
I'll be sending an automatic PR with the latest version to all track repos. Stay tuned! :)

**Comment by mpizenberg** [comment]
Replaced by #16

**Pull request closed without merging**
