### PR TITLE
Extract test code

### PR DESCRIPTION
**Pull request by ceddlyburge**

### CODE REVIEW

**Review by mpizenberg — COMMENTED** [review]
Hi @ceddlyburge , I've just had a first quick read and run of the extractor and it seems to be working well, with some quirks. I'll try later (maybe tomorrow) to have a more detailed look but from what I've seen for now I have some remarks regarding the output.

Let's take "BettysBikeShop" tests as an example, slightly modified by adding `describe "1"` and `describe "2"` to group them by tasks as discussed last time. So the tests code is the following.


```elm
tests : Test
tests =
    describe "BettysBikeShop"
        [ describe "1"
            [ test "599 pence should be 5.99 pounds" <|
                \_ ->
                    penceToPounds 599
                        |> Expect.within (Absolute 0.001) 5.99
            , test "33 pence should be 0.33 pounds" <|
                \_ ->
                    penceToPounds 33
                        |> Expect.within (Absolute 0.001) 0.33
            ]
        , describe "2"
            [ test "5.99 pounds should be formatted as £5.99" <|
                \_ ->
                    poundsToString 5.99
                        |> Expect.equal "£5.99"
            , test "0.33 pounds should be formatted as £0.33" <|
                \_ ->
                    poundsToString 0.33
                        |> Expect.equal "£0.33"
            ]
        ]
```

Then the output of

```sh
elm-test-rs --report exercism
```

currently is:

```json
{
  "version": 2,
  "status": "fail",
  "tests": [
    {
      "name": "BettysBikeShop > 1 > 599 pence should be 5.99 pounds",
      "status": "fail",
      "message": "\n    This test failed because it threw an exception: \"Error: TODO in module `BettysBikeShop` on line 9\n    \n    implement this function and create a type annotation\"\n\n",
      "output": null,
      "test_code": null
    },
    {
      "name": "BettysBikeShop > 1 > 33 pence should be 0.33 pounds",
      "status": "fail",
      "message": "\n    This test failed because it threw an exception: \"Error: TODO in module `BettysBikeShop` on line 9\n    \n    implement this function and create a type annotation\"\n\n",
      "output": null,
      "test_code": null
    },
    {
      "name": "BettysBikeShop > 2 > 5.99 pounds should be formatted as £5.99",
      "status": "fail",
      "message": "\n    This test failed because it threw an exception: \"Error: TODO in module `BettysBikeShop` on line 13\n    \n    implement this function and create a type annotation\"\n\n",
      "output": null,
      "test_code": null
    },
    {
      "name": "BettysBikeShop > 2 > 0.33 pounds should be formatted as £0.33",
      "status": "fail",
      "message": "\n    This test failed because it threw an exception: \"Error: TODO in module `BettysBikeShop` on line 13\n    \n    implement this function and create a type annotation\"\n\n",
      "output": null,
      "test_code": null
    }
  ]
}
```

So essentially, if we want to be able to easily combine the output of `extract-test-code` with the one of the tests results, we should output a JSON string in `extract-test-code` that has the same structure. So basically, we should output something like this:

```json
[
  {
    "name": "BettysBikeShop > 1 > 599 pence should be 5.99 pounds",
    "test_code": "... all the stuff here ..."
  },
  {
    "name": "BettysBikeShop > 2 > 5.99 pounds should be formatted as £5.99",
    "test_code": "... all the stuff here ..."
  },
  ...
]
```

Also, I'll remove all the non-final describe parts of tests "name" because it adds noise in the interface. So when I update elm-test-rs for the exercism report, I'll put just "599 pence should be 5.99 pounds" in the "name" and remove the "BettysBikeShop > ". This will make the output cleaner for students and the JSON generation of extract-test-code simpler.

I feel we are getting there! Let me know what you think of those remarks and of course thanks a lot for that work!

**Comment by ceddlyburge** [comment]
Hi Matthieu, it sounds like the ask is to change the test description / name, to include the string from `describe`

This is definitely doable, but if you are changing elm-test-rs anyway, I feel like it might make more sense to just use the test name (and require that it be unique, which I think is something elm-test-rs already requires). Adding the "1 >" type text won't look as slick for the students, and I think the exercism test output already has a `task_id` property for this purpose.

**Comment by mpizenberg** [comment]
No you're right sorry. Indeed I'll change the `name` in elm-test-rs to return only the last describe component, just as you do in this extractor so you don't need to change that. What I failed to say was the focus on the JSON output with a `name` and `test_code` fields so that we can easily merge both outputs with `jq` for each matching `name` field, later in the `run.sh` script.

**Comment by mpizenberg** [comment]
Here is how we might merge the two later (after I upgrade elm-test-rs) : https://stackoverflow.com/questions/54956517/use-jq-to-combine-two-arrays-of-objects-on-a-certain-key

**Comment by mpizenberg** [comment]
I've updated elm-test-rs to v1.1 with the new "task_id" detection and using only the last describe component for "name". So you can now test directly in this PR the integration with the test code extractor.

**Comment by ceddlyburge** [comment]
Ok, so to get this pull request to a mergeable state, I think I need to change the output, to something like this, right?

```
[
  {
    "name": "599 pence should be 5.99 pounds",
    "test_code": "... all the stuff here ..."
  },
  {
    "name": "5.99 pounds should be formatted as £5.99",
    "test_code": "... all the stuff here ..."
  },
  ...
]
```

I don't think this will be a big deal, we already have the name and the test code, its just a case of formatting the output a little differently (and escaping the code).

**Comment by mpizenberg** [comment]
Yep exactly. No need to do much work for escaping even, it's enough to make it an encoder and then call `Json.Encode.encode 2`

**Comment by mpizenberg** [comment]
For a data structure like:
```elm
type alias ExtractedTest =
    { name : String
    , testCode : String
    }

encode : ExtractedTest -> Value
encode = Encode.object ...
```

**Comment by ceddlyburge** [comment]
HI Matthieu, the code now outputs the results in the required json format. I think there is still some work to do to integrate it and use it with the test runner / elm-test-rd

**Review by mpizenberg — APPROVED** [review]
I've added the `jq` magic to merge test results with the extracted test code. I've haven't fully read the code but the behavior seems good!
One tiny weird thing is the additional empty line after the `let` for tests using a `let ... in`.

Let me know what you think @ceddlyburge and if you see something wrong while testing it with actual example solutions of various shapes.

**Comment by mpizenberg** [comment]
By the way, the `jq` magic that merges the extracted code with the tests results might interest @ErikSchierboom and @iHiD as an example for other people in the same situation as ours, that is with the extracted code in a different json file:
https://github.com/exercism/elm-test-runner/pull/21/files#diff-00a80c5821edea2ebf676056aa4c9a24e57379ef52cefecb2ccffaaf4cc362c9R68

**Comment by ceddlyburge** [comment]
> One tiny weird thing is the additional empty line after the let for tests using a let ... in.

This comes from the way elm-syntax formats the output. We could probably submit a bug request, or a PR to the repo, they were very prompt last time there was a problem

**Comment by ceddlyburge** [comment]
> Let me know what you think @ceddlyburge and if you see something wrong while testing it with actual example solutions of various shapes.

It all looks good to me, although I haven't tested it. I'm in favour of merging and testing with some example solutions.

**Comment by mpizenberg** [comment]
Actually there is a problem with the order of tests after the merge. It seems `jq` command `group_by` sort elements by the corresponding key (`"name"` here) and so the order of tests is not preserved :( I'll see if I can find an alternative

**Comment by ceddlyburge** [comment]
If not maybe we can do something in node ...

**Comment by mpizenberg** [comment]
Alright, I've fixed the order, then fixed the bug I introduced in the fix, then fixed a forgotten `version: 2` in the error case.
Finally, I think we are good now.

**Comment by ceddlyburge** [comment]
Skillz :)

**Comment by mpizenberg** [comment]
Stackoverflow skilzzzz :)

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
